### ISSUE TITLE
Increment doctrine-module version to 0.9

### ISSUE THREAD

**Issue by aight8** [doctrine/DoctrineMongoODMModule#117]
"doctrine/doctrine-module": "0.8.*"

Is it possible to increment the required doctrine module version to 0.9 since doctrine ORM requires this version too. So it's impossible to install both without a custom fork or hack.

**Comment by bicatu** [comment]
I've been trying to update my setup and now I get : doctrine/doctrine-mongo-odm-module dev-master requires doctrine/doctrine-module 0.9.* -> no matching package found

**Comment by babarinde** [comment]
@Ocramius @bicatu am having this issue as well
doctrine/doctrine-mongo-odm-module dev-master requires doctrine/doctrine-module 0.9.* -> satisfiable by doctrine/doctrine-module[0.9.x-dev]

**Comment by gianarb** [comment]
I close this issues.
Now the master branch support doctrine-module 0.9.* 
You can see this commit 322a8ca

Thanks!
