### ISSUE TITLE
Error updating with composer

### ISSUE THREAD

**Issue by amamut** [doctrine/DoctrineMongoODMModule#119]
Running an update with composer and getting this error:

doctrine/doctrine-mongo-odm-module dev-master requires doctrine/doctrine-module 0.9.* -> no matching package found.

This was working just fine a few days ago.

**Comment by bicatu** [comment]
This is happening to me as well

**Comment by gaellm** [comment]
Same problem here

**Comment by bensquire** [comment]
Same here. Looking at https://github.com/doctrine/DoctrineModule the highest version they're on is 0.8.0-beta2

**Comment by bicatu** [comment]
I've managed to make it work by adding this to my composer.json

"doctrine/doctrine-module": "0.9.x-dev",


So it is like this

"require": {        "php": ">=5.3.3",
"zendframework/zendframework": "2.3.*",
"doctrine/doctrine-mongo-odm-module": "dev-master",
"doctrine/doctrine-module": "0.9.x-dev",
"doctrine/data-fixtures": "1.0.*@dev"    }

**Comment by amamut** [comment]
@bicatu solution works.

**Comment by gianarb** [comment]
I close this issues..
Now the master branch support doctrine-module 0.9.* and php >= 5.4
