### ISSUE TITLE
Change database connection dynamically

### ISSUE THREAD

**Issue by navneetccna** [doctrine/DoctrineMongoODMModule#129]
Hi i want to connection multiple database on multiple serve can i change connection setting on run time

**Comment by Ocramius** [comment]
That is not allowed by the ODM itself. Instead, create a custom connection
object and switch connection in there.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by navneetccna** [comment]
not understand can you please provide an example or more detail about it ?

**Comment by navneetccna** [comment]
asked this question on stackoverflow but still no solution found 

http://stackoverflow.com/questions/30440143/change-database-connection-dynamically-in-doctrine-doctrinemongoodmmodule#

**Comment by gianarb** [comment]
Use stackoverflow

i close this issue
Thanks!
