### ISSUE TITLE
How to get data from multiple collection in loop

### ISSUE THREAD

**Issue by navneetccna** [doctrine/DoctrineMongoODMModule#130]
when i try to get data from multiple collection code giving me data only from first collection
i.e collection are project_0, project_1, project_2, project_3

```php
for($i = 0; $i <= 3; $i++){
$dm->getClassMetadata('\Application\Document\Product')->setCollection('product_'. $i);
$record = $dm->getRepository('\Application\Document\Product')->findOneBy($condition);
}
```

i tried clear flush but noting is working please let me know right way to do it

**Comment by Ocramius** [comment]
Not an ODM module issue.

Also, modifying metadata at runtime is not supported.

**Comment by navneetccna** [comment]
i am not saying it is bug but how to achieve it if i want to get data from multiple collection and what is the use of clear and flush methods ?

**Comment by Ocramius** [comment]
This is not a scenario supported by the ODM. If you need to fetch data from different collections, then you'd map 3 different documents.

Anyway, for questions, please try on http://stackoverflow.com/ first

**Comment by navneetccna** [comment]
already searched on stackoverflow but not get any solution how to map 3 different documents.

**Comment by Ocramius** [comment]
If you don't find a solution on stackoverflow, then you should probably ask
for one there ;-)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by navneetccna** [comment]
ok

**Comment by navneetccna** [comment]
asked this question on stackoverflow but still no solution 

http://stackoverflow.com/questions/30440092/how-to-get-data-from-multiple-collection-in-loop

can you help me on this ?
