### ISSUE TITLE
Help error composer install

### ISSUE THREAD

**Issue by levinhne** [doctrine/DoctrineMongoODMModule#131]
Help error composer install.

 Problem 1
    - Installation request for doctrine/doctrine-mongo-odm-module dev-mast
er -> satisfiable by doctrine/doctrine-mongo-odm-module[dev-master].
    - doctrine/doctrine-mongo-odm-module dev-master requires doctrine/doct
rine-module 0.9.* -> no matching package found.

Thanks!

**Comment by gianarb** [comment]
I don't remember this upgrade of DoctrineModule.. 0.9 not exists..

This stuff same a bug.. In this moment I am not in office.. I can try to check it this evening..
Thanks and sorry

**Comment by gianarb** [comment]
@levinhne can you try to run composer self-update before composer update? Thanks a lot..

**Comment by NewtonsNerds** [comment]
+1. Tried everything above, still same error.

**Comment by gianarb** [comment]
Try composer selfupdate

**Comment by FaMa91** [comment]
Same problem, something new?

**Comment by gianarb** [comment]
I have not this problem.. Can you try to run
```
composer selfupdate
composer clearcache
```
?? Thanks

**Comment by FaMa91** [comment]
done, same problem

**Comment by gianarb** [comment]
Can you share here your composer.json please?
THanks a lot

**Comment by FaMa91** [comment]
{
    "name": "x application",
    "description": "x Application",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://www.x.it/",
    "minimum-stability": "alpha",
    "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.4.x",
        "zendframework/zend-developer-tools": "dev-master",
        "bjyoungblood/bjy-authorize": "1.4.*",
        "zf-hipsters/bootstrap-flash-messenger": ">=1.0",
        "zf-commons/zfc-base": "0.*",
        "zf-commons/zfc-user": "dev-master",
	"rwoverdijk/assetmanager": "1.*",
        "mvlabs/mvlabs-snappy": "dev-master",
        "jfloff/highroller-zf2": "dev-master",
	"doctrine/doctrine-mongo-odm-module": "dev-master"


	
        
	
    },
    "require-dev":{
      "zendframework/zftool": "dev-master"
    }


}

**Comment by gianarb** [comment]
Sorry can you paste this composer.json with a correct syntax?
Why do you require zf-commons/zfc-base 0. ? :)

Thanks

**Comment by gianarb** [comment]
I tried this solution and it works
```json
{
  "name": "x application",
  "description": "x Application",
  "license": "BSD-3-Clause",
  "keywords": [
    "framework",
    "zf2"
  ],
  "homepage": "http://www.x.it/",
  "minimum-stability": "alpha",
  "require": {
    "php": ">=5.3.3",
    "zendframework/zendframework": "2.4.x",
    "zendframework/zend-developer-tools": "dev-master",
    "bjyoungblood/bjy-authorize": "1.4.",
    "zf-hipsters/bootstrap-flash-messenger": ">=1.0",
    "zf-commons/zfc-base": "~0.1.0",
    "zf-commons/zfc-user": "dev-master",
    "rwoverdijk/assetmanager": "1.*",
    "mvlabs/mvlabs-snappy": "dev-master",
    "jfloff/highroller-zf2": "dev-master",
    "doctrine/doctrine-mongo-odm-module": "0.8.2"
  },
  "require-dev":{
      "zendframework/zftool": "dev-master"
  }
}
```
