### ISSUE TITLE
Setting read preference in configuration ?

### ISSUE THREAD

**Issue by dorongutman** [doctrine/DoctrineMongoODMModule#134]
How do I set the read preference in the config files ? i.e. module.doctrine-mongo-odm.local.php

**Comment by gianarb** [comment]
Yes you can it into connection key..
Read this chapter
https://github.com/doctrine/DoctrineMongoODMModule
and the official docs
http://www.php.net/manual/en/mongoclient.construct.php

**Comment by dorongutman** [comment]
You mean in the "options" array of the "connection" section ?

**Comment by gianarb** [comment]
Hi yes..
Your configuation array accepts an options key.. 
```php
array(
connection' => array(
            'odm_default' => array(
                'server'           => 'localhost',
                'port'             => '27017',
                'connectionString' => null,
                'user'             => null,
                'password'         => null,
                'dbname'           => null,
                'options'          => array()
            ),
        )
)
```

**Comment by dorongutman** [comment]
Great, thanks.
