### ISSUE TITLE
Mongoid strategy issue

### ISSUE THREAD

**Issue by navneetccna** [doctrine/DoctrineMongoODMModule#137]
when i use following mongoid strategy

/** @ODM\Id(strategy="NONE") */

$id = '50e6c53cf8ae035c1b000001';
                $User->setId($id);

id inserted successfully in collection but getting following error

<b>Warning</b>:  Illegal offset type in <b>vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php</b> on line <b>1565</b><br />

**Comment by malarzm** [comment]
@gianarb not necessarily a bug, cross referencing my questions for @navneetccna in https://github.com/doctrine/mongodb-odm/issues/1167#issuecomment-119572797

**Comment by gianarb** [comment]
oh yes @malarzm I have tagged this issue how bug to remember me to check it :)

I'm following doctrine/mongodb-odm's issue! :) Thanks

**Comment by malarzm** [comment]
Most probably if the issue exists it will be in ODM so you can even close this ticket ;)

**Comment by gianarb** [comment]
Ok thanks! :)
