### ISSUE TITLE
Installation with composer fails

### ISSUE THREAD

**Issue by jameslovegrove** [doctrine/DoctrineMongoODMModule#139]
I have just begun building a new ZF2 application. My first task is always to install DoctrineMongoODMModule, except that today it is not working.

  Problem 1
    - Installation request for doctrine/doctrine-mongo-odm-module dev-master -> satisfiable by doctrine/doctrine-mongo-odm-module[dev-master].
    - doctrine/doctrine-mongo-odm-module dev-master requires doctrine/mongodb-odm 1.0.*@dev -> no matching package found.

**Comment by gianarb** [comment]
Hi! I started now my project by ZendSkeletonApplication with this composer.json configuration..
```json
{
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for ZF2",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://framework.zend.com/",
    "require": {
        "php": ">=5.5",
        "doctrine/doctrine-mongo-odm-module": "0.9.0",
        "zendframework/zendframework": "~2.5"
    }
}
```
For me work can you try to clean composer cache?
```
composer clearcache
composer install
```
Thanks

**Comment by Danielss89** [comment]
I can confirm this too, with newest composer and a cleared cache.
```
composer --version
Composer version 1.0-dev (00c26791faeb83da8476b54bcc20596cf754362e) 2015-07-20 17:29:14
```
```
composer update          
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-mongo-odm-module ~0.9.0 -> satisfiable by doctrine/doctrine-mongo-odm-module[0.9.0].
    - doctrine/doctrine-mongo-odm-module 0.9.0 requires doctrine/mongodb-odm 1.0.*@dev -> no matching package found.
```

**Comment by gianarb** [comment]
Can you try with 0.9.1? Thanks a lot!

**Comment by Danielss89** [comment]
Hmm, i'm still getting
```
 Problem 1
    - Installation request for doctrine/doctrine-mongo-odm-module 0.9.1 -> satisfiable by doctrine/doctrine-mongo-odm-module[0.9.1].
    - doctrine/doctrine-mongo-odm-module 0.9.1 requires doctrine/mongodb-odm 1.0.*@dev -> no matching package found.
```

**Comment by gianarb** [comment]
From the README of this module
`"minimum-stability": "alpha",`

do you use it in your composer.json? ex I use dev and work

**Comment by Danielss89** [comment]
Arg, knew i was missing something. Yes that works

**Comment by gianarb** [comment]
![relief](https://cloud.githubusercontent.com/assets/1630267/8795646/ef84e222-2f8e-11e5-90d7-a9807a6ca447.gif)

wow! I thought to be crazy! :laughing:

**Comment by ramyay** [comment]
thank you, it worked for me too
