### ISSUE TITLE
How to use multiple connection

### ISSUE THREAD

**Issue by navneetccna** [doctrine/DoctrineMongoODMModule#143]
What is meaning of 

Multiple document managers
Multiple connections

and how to use these features ?

**Comment by lucasalves** [comment]
@navneetccna you have an answer for that?

I have the same doubts

**Comment by TomHAnderson** [comment]
By default this module creates a `doctrine.documentmanager.odm_default` object manager.  If you want multiple database connections then each database connection needs to be assigned to a unique  object manager.

I don't have an example for ODM but here's a ORM example:  https://blog.tomhanderson.com/2016/03/zf2-doctrine-configure-second-object.html
