### ISSUE TITLE
Problem in find condition with collection and hash

### ISSUE THREAD

**Issue by navneetccna** [doctrine/DoctrineMongoODMModule#145]
my condition is : `workflow_settings.assignees.user_id = '50e6c53cf8ae035c1b000001'`
when insert data with collection property condition not working but if convert in to hash it start working

when insert data with hash property condition not working even if i convert in collection type

Data Array

```
[workflow_settings] => Array
(
    [0] => Array
        (
            [to_company] => 54b925f61ebe95e86c8b4567
            [approved_status] => false
            [status] =>
            [assignees] => Array
                (
                    [0] => Array
                        (
                            [user_id] => 50e6c53cf8ae035c1b000001
                            [name] => Ravindra Chouhan
                            [email] => rchouhan@intellobuild.com
                            [status] =>
                            [date] =>
                        )

                    [1] => Array
                        (
                            [user_id] => 5264be641ebe951e118b4568
                            [name] => Jackub Joe
                            [email] => jackub@gmail.com
                            [status] =>
                            [date] =>
                        )

                )
        )
)

Data Json

"workflow_settings": [
     {
       "to_company": "54b925f61ebe95e86c8b4567",
       "approved_status": "false",
       "status": "",
       "assignees": [
         {
           "user_id": "50e6c53cf8ae035c1b000001",
           "name": "Ravindra Chouhan",
           "email": "rchouhan@intellobuild.com",
           "status": "",
           "date": ""
        },
         {
           "user_id": "5264be641ebe951e118b4568",
           "name": "Jackub Joe",
           "email": "jackub@gmail.com",
           "status": "",
           "date": ""
        }
      ]
    }
}
```

**Comment by navneetccna** [comment]
my condition working in normal php mongodb find and also in rockmongo

**Comment by Ocramius** [comment]
@navneetccna closing this, as it is not clear how this is related to DoctrineMongoODMModule

**Comment by navneetccna** [comment]
because normal find query working but with findBy failed to show data with the same condition

**Comment by Ocramius** [comment]
Still unrelated with the module itself. You may want to try writing a test
case against the ODM itself instead.

**Comment by navneetccna** [comment]
so it is related to mongodb-odm then ?

**Comment by Ocramius** [comment]
Yes, but the way you reported it initially would still have insufficient
information for an actual bug report...

**Comment by navneetccna** [comment]
ok then what information i have to provide ?

**Comment by Ocramius** [comment]
A test case :-)

**Comment by navneetccna** [comment]
how to write a test case ?

**Comment by malarzm** [comment]
@navneetccna you can refer to tests like https://github.com/doctrine/mongodb-odm/blob/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1117Test.php in ODM itself.

**Comment by navneetccna** [comment]
ok thanks i'll try to write a test case and then submit
