### ISSUE TITLE
Can't install using PHP7

### ISSUE THREAD

**Issue by fabiopaiva** [doctrine/DoctrineMongoODMModule#154]
Problem:
    doctrine/doctrine-mongo-odm-module 0.9.1 requires doctrine/mongodb-odm 1.0
    doctrine/mongodb-odm 1.0.0-BETA6 requires doctrine/mongodb
    doctrine/mongodb 1.0.x-dev requires ext-mongo >=1.2.12,<1.7-dev -> the requested PHP extension mongo is missing from your system.

When i tried to install mongodb:

    sudo pecl install mongo
    
    WARNING: "pecl/mongo" is deprecated in favor of "channel:///mongodb"
    pecl/mongo requires PHP (version >= 5.3.0, version <= 5.99.99), installed version is 7.0.2-4+deb.sury.org~trusty+1
    No valid packages found
    install failed

**Comment by malarzm** [comment]
Unfortunately ODM itself doesn't work with PHP7, for more details please see https://github.com/doctrine/mongodb-odm/issues/1292

**Comment by gianarb** [comment]
Remember to close this issue if you are ok! :)
Thanks @malarzm

**Comment by fabiopaiva** [comment]
:(
