### ISSUE TITLE
get was unable to fetch or create an instance for doctrine.odm.documentmanager.default

### ISSUE THREAD

**Issue by tux-rampage** [doctrine/DoctrineMongoODMModule#158]
This fails for 1.0.x, 0.9.x and dev-master (which seems to be 0.9???)
- The config in branch 1.0.x is compatible with doctrine/doctrine-module. The config in dev-master is not.
- The service factories in 1.0.x are incompatible with doctrine/doctrine-module (missing), The service factories in dev-master are compatible, but lacking definition in doctrine_factories key (besides incompatible config)

This module can be considered to be severely broken.

**Comment by alcaeus** [comment]
Sorry for the long delay here. Is this still relevant? If so, could you provide a failing test case so I can fix this?

**Comment by tux-rampage** [comment]
I will have to check it, since its been a while. Since I switched to ZendExpresive, I don't use it in any recent projects.

**Comment by alcaeus** [comment]
Closing due to lack of feedback. Feel free to reopen if the issue persists.
