### ISSUE TITLE
Custom collection support

### ISSUE THREAD

**Issue by Bilge** [doctrine/DoctrineMongoODMModule#163]
There appears to be no support for custom collections, including, but not limited to: configuration support and command line generation support.

**Comment by malarzm** [comment]
FWIW relevant PRs for Symfony's bundle: https://github.com/doctrine/DoctrineMongoDBBundle/pull/345 and https://github.com/doctrine/DoctrineMongoDBBundle/pull/371

**Comment by alcaeus** [comment]
I'll close this since we have PR to discuss changes. Thanks @Bilge!
