### ISSUE TITLE
Wrong service alias 'Doctrine\ODM\Mongo\DocumentManager' in config

### ISSUE THREAD

**Issue by 4orever** [doctrine/DoctrineMongoODMModule#170]
It should be 'Doctrine\ODM\MongoDb\DocumentManager' (it is correct class name) or even better Doctrine\ODM\Mongo\DocumentManager::class. So we don't need to remember full string and just can use IDE autocomplete by class name.

**Comment by alcaeus** [comment]
This will be fixed in #150.

**Comment by alcaeus** [comment]
Fixed in 1.0.
