### ISSUE TITLE
RFC 2396 conformant escaping of username and password

### ISSUE THREAD

**Issue by functionistic** [doctrine/DoctrineMongoODMModule#171]
When configuring the connection parameters via the module config file (DoctrineMongoODMModule/config/module.doctrine-mongo-odm.local.php.dist) and instead of using the connection string variant the separate fields for server, username, password, etc. are used, it is not obvious for a user that he has to provide these strings in an escaped form. For example when he uses a password containing a '@' character.

**Comment by TomHAnderson** [comment]
Closing this due to age.
