### ISSUE TITLE
doctrine/doctrine-mongo-odm-module 0.8.2 requires doctrine/mongodb-odm ~1.0.0-beta9@dev -> no matching package found.

### ISSUE THREAD

**Issue by mrverak** [doctrine/DoctrineMongoODMModule#179]
Here is my project composer.json
----
"require": {
        "php": ">=5.3.3",
		"zendframework/zendframework": "2.2.10",
		"developerforce/force.com-toolkit-for-php": "v27.0.3",
		"elasticsearch/elasticsearch": "~1.0",
		"doctrine/doctrine-mongo-odm-module": "0.8.x",
        "phpoffice/phpexcel": "1.8.0"
}
When i run update composer on live i get this error, also want to say it is running fine in local dev.
----
[Composer\DependencyResolver\SolverProblemsException]Problem 1- Installation request for doctrine/doctrine-mongo-odm-module 0.8.x -> satisfiable by doctrine/doctrine-mongo-odm-module[0.8.2].- doctrine/doctrine-mongo-odm-module 0.8.2 requires doctrine/mongodb-odm ~1.0.0-beta9@dev -> no matching package found.Potential causes:- A typo in the package name- The package is not available in a stable-enough version according to your minimum-stability

Please help how i can solve it?

**Comment by alcaeus** [comment]
Please don't lock specific versions. You should use `doctrine/doctrine-mongo-odm-module": "^0.11"`, which will also install a stable version of doctrine/mongodb-odm.

**Comment by mrverak** [comment]
if you go here https://packagist.org/packages/doctrine/doctrine-mongo-odm-module#0.8.2 here is a dependency is **doctrine/mongodb-odm: ~1.0.0-beta9@dev** and when you this package here mongodb-odm package https://packagist.org/packages/doctrine/mongodb-odm you will find that **doctrine/mongodb-odm: ~1.0.0-beta9@dev** version is not available.

is it can be a reason? @alcaeus  i edited according to your comment but not successed
Many thanks

**Comment by alcaeus** [comment]
0.8.2 is almost two years old, Beta-9 is almost 4 years old. We're no longer supporting these versions, please upgrade to Module 0.11 and ODM 1.1.

If changing the requirement does not work, please post an error message so I can help you figure out what's going on. Thanks.

**Comment by alcaeus** [comment]
Closing due to lack of feedback.
