### ISSUE TITLE
How can we write mongo query directly in doctorine ODM

### ISSUE THREAD

**Issue by sarathiscookie** [doctrine/DoctrineMongoODMModule#188]
I am trying to fetch data from 2 documents with $lookup method. I tried with doctrine ODM 'createAggregateBuilder' and it shows the below message, Is there any possibility to add 'native mongo query' in doctrine ODM. Do we have any another option to write $lookup method in ODM.

( ! ) Fatal error: Call to undefined method Doctrine\ODM\MongoDB\DocumentManager::createAggregationBuilder()

I am using composer package given below
"doctrine/doctrine-mongo-odm-module": "dev-master",

Query:-
$builder = $em->createAggregationBuilder('Booking\Document\Booking');
$builder
    ->lookup('user')
        ->alias('user')
    ->unwind('$user');

**Comment by malarzm** [comment]
@sarathiscookie `createAggregationBuilder` is available in unreleased (yet) 1.2 version of ODM. You need to require `dev-master` of ODM itself to use the feature.

**Comment by TomHAnderson** [comment]
createAggregationBuilder is in 1.3.6.  Closing.
