### ISSUE TITLE
Annotation Driver not reading documents correct?

### ISSUE THREAD

**Issue by Willzyc** [doctrine/DoctrineMongoODMModule#189]
I am trying to run both, the ORM and ODM together. The ORM works fine, but the ODM is not reading my annotations.

I have the following configuration:

Connection (I dont think this is the problem, but to have everything covered here):

`'doctrine' => [

        'connection' => [
            'orm_default' => [
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => [
                    'host'     => 'mysql',
                    'port'     => '3306',
                    'user'     => '***',
                    'password' => '***',
                    'dbname'   => '***',
                    'charset' => 'utf8',
                    'driverOptions' => [
                        1002 => 'SET NAMES utf8',
                    ],
                ],
            ],
            'odm_default' => [
                'server'           => 'mongodb',
                'port'             => '27017',
                'user'             => '***',
                'password'         => '***',
                'dbname'           => '***',
                'options'          => [],
            ],
        ],
    ],`

Modules imported (should also be fine):

`
    	'DoctrineModule',
        'DoctrineMongoODMModule',
    	'DoctrineORMModule',`

Here the driver configuration:

Entities are working fine, but documents keep throwing errors:
Class Games\Document\Game is not a valid document or mapped super class.

I assume the paths are correct in my directory structure, because entities work.

```<?php

namespace Games;

return [

'doctrine' => [
      'driver' => [
          __NAMESPACE__ . '\ORMDriver' => [
                'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'cache' => 'array',
                'paths' => [
                    __DIR__ . '/../src/' . __NAMESPACE__ . '/Entity',
                ],
            ],
            'orm_default' => [
                'drivers' => [
                    __NAMESPACE__ . '\Entity' => __NAMESPACE__ . '\ORMDriver',
                ],
            ],
            __NAMESPACE__ . '\ODMDriver' => [
                'class' => 'Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver',
                'cache' => 'array',
                'paths' => [
                    __DIR__ . '/../src/' . __NAMESPACE__ . '/Document',
                ],
            ],
            'odm_default' => [
                'drivers' => [
                    __NAMESPACE__ . '\Document' => __NAMESPACE__ . '\ODMDriver',
                ],
            ],
        ],
    ],
];
```

Here my document class, nothing special, very basic for testing:

```
namespace Games\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/*
 * @ODM\Document(
 *     collection="game", 
 *     repositoryClass="Games\Repository\Game"
 * ) 
 */
class Game
{
    /**
     * @ODM\Id(strategy="UUID")
     */
    protected $id;

    /**
     * @ODM\Field(type="string") 
     */
    protected $name;

    /** 
     * @ODM\Field(type="string") 
     */
    protected $namespace;
    
    /** 
     * @ODM\Field(type="string") 
     */
    protected $logo;

    public function __construct(string $name, string $namespace, string $logo)
    {
        $this->name = $name;
        $this->namespace = $namespace;
        $this->logo = $logo;
    }

    public function toArray()
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'namespace' => $this->namespace,
            'logo' => $this->logo,
        ];
    }
}
```

The collection game exists and the repository class also

**Comment by TomHAnderson** [comment]
@Willzyc I'm trying to close some old tickets.  Did you ever find a resolution to this and was it a configuration issue or something in the library?

**Comment by TomHAnderson** [comment]
Closing due to age.
