### ISSUE TITLE
DoctrinePaginator is not working with  CommandCursor returned from ODM Aggregation Builder

### ISSUE THREAD

**Issue by metanav** [doctrine/DoctrineMongoODMModule#190]
I guess DoctrinePaginator does not support CommandCursor.

```
$results     = $aggregationBuilder->execute();
$paginator = new DoctrineMongoODMModule\Paginator\Adapter\DoctrinePaginator($results);

```

Argument 1 passed to DoctrineMongoODMModule\Paginator\Adapter\DoctrinePaginator::__construct() must be an instance of Doctrine\ODM\MongoDB\Cursor, instance of Doctrine\ODM\MongoDB\CommandCursor given

**Comment by TomHAnderson** [comment]
Will not address in mongodb-odm ^1.3
