### ISSUE TITLE
Connection failed if username or password contains '@'

### ISSUE THREAD

**Issue by Skpd** [doctrine/DoctrineMongoODMModule#194]
https://github.com/doctrine/DoctrineMongoODMModule/blob/master/src/DoctrineMongoODMModule/Service/ConnectionFactory.php#L58

Connection string created by default with username and password, but it will failed to connect for something like 

> mongodb://user:p@ssW0rd@dbhost:27017/dbname

Username and password should be passed as options instead.

**Comment by malarzm** [comment]
@Skpd are you willing to work on a PR fixing this?

**Comment by Skpd** [comment]
@malarzm ok, I can do that

**Comment by TomHAnderson** [comment]
Closed with no action.
