### ISSUE TITLE
Allow DoctrineModule ^2.1

### ISSUE THREAD

**Issue by TomHAnderson** [doctrine/DoctrineMongoODMModule#196]
The latest DoctrineModule is 2.1.0.  This is outside the current requirement of ^1.2

Please change this in your composer.json file and release a new version.  

There are several applications which support both this and DoctrineORMModule which also use DoctrineModule 2.1.0 making a fix for this a high priority IMHO.

**Comment by alcaeus** [comment]
I can take a look at it, is there anything significant that might break when switching to 2.1?

**Comment by TomHAnderson** [comment]
1. Hydrators have moved from Zend\Stdlib\Hydrator to Zend\Hydrator

2. I think this needs to change to support only PHP ^7.1 http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/introduction.html#using-php-7 http://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

3. I guess you could just up to ^2.1 for doctrine-module but I think the correct course of action is to move the library forward to PHP ^7.1

**Comment by YuraKril** [comment]
Are there any updates?

**Comment by MaximOrlovsky** [comment]
vote for this feature, it's really valuable and important thing.

may the humble donate will help to push it forward?

**Comment by YuraKril** [comment]
Do you have any update ?
@alcaeus

**Comment by alcaeus** [comment]
> Do you have any update ?

No - I would've said otherwise. My focus is currently on finishing up ODM 2.0, which means that other things have to wait. If you need it urgently, feel free to give it a shot and send a pull request. Thanks for understanding.
