### ISSUE TITLE
Getting error after configure the the ODM

### ISSUE THREAD

**Issue by raviguptaa3** [doctrine/DoctrineMongoODMModule#201]
Hello,

I have configure this module in zend framework 2 as given steps but I am getting the error which is 

Fatal error: Uncaught Zend\Stdlib\Exception\BadMethodCallException: The option "odm_driver" does not have a callable "setOdmDriver" ("setodmdriver") setter method which must be defined in /zf/vendor/zendframework/zend-stdlib/src/AbstractOptions.php:112 Stack trace: #0 /zf/vendor/zendframework/zend-stdlib/src/AbstractOptions.php(64): Zend\Stdlib\AbstractOptions->__set('odm_driver', Array) #1 /zf/vendor/zendframework/zend-stdlib/src/AbstractOptions.php(34): Zend\Stdlib\AbstractOptions->setFromArray(Array) #2 /zf/vendor/doctrine/doctrine-module/src/DoctrineModule/Service/AbstractFactory.php(112): Zend\Stdlib\AbstractOptions->__construct(Array) #3 /zf/vendor/doctrine/doctrine-module/src/DoctrineModule/Service/DriverFactory.php(48): DoctrineModule\Service\AbstractFactory->getOptions(Object(Zend\ServiceManager\ServiceManager), 'driver') #4 /zf/vendor/doctrine/doctrine-module/src/DoctrineModule/Service/DriverFactory.php(58 in /zf/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 941

Below is the code
```

 'doctrine' => array(
            'driver' => array(
                    // defines an annotation driver with two paths
                     'Application_driver' => array(
                            'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                            'cache' => 'array',
                           // 'paths' => array(__DIR__ . '/../src/' . __NAMESPACE__ . '/Entity'),
                         'paths' => array(__DIR__ . '/../src/Application/Entity'),
                    ),

                    // default metadata driver, aggregates all other drivers into a single one.
                    // Override `orm_default` only if you know what you're doing
                    'orm_default' => array(
                            'drivers' => array(
                                     'Application\Entity' => 'Application_driver',
                    ),

                    'odm_driver' => array(
                        'class' => 'Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver',
                        'paths' => array(__DIR__ . '/../src/Application/Document')
                    ),
                    'odm_default' => array(
                        'drivers' => array(
                            'Application\Document' => 'odm_driver'
                        )
                    )
                ),
            ),

```
Here I am configuring the ORM and ODM both

**Comment by TomHAnderson** [comment]
```
         'orm_default' => array(
                            'drivers' => array(
                                     'Application\Entity' => 'Application_driver',
                    ),
```
This code is missing the closing array parentheses.
