### ISSUE TITLE
Missing defaultRepositoryClassName attribute

### ISSUE THREAD

**Issue by mdjaman** [doctrine/DoctrineMongoODMModule#204]
Hello can you please expose the attribute ```defaultRepositoryClassName``` in `module.doctrine-mongo-odm.global.php`

**Comment by TomHAnderson** [comment]
The configuration setter has changed

public function setDefaultRepositoryClassName($className)

@deprecated in version 1.2 and will be removed in 2.0. Please use setDefaultDocumentRepositoryClassName instead.

**Comment by TomHAnderson** [comment]
Fixed
