### ISSUE TITLE
ODM 2.0 support?

### ISSUE THREAD

**Issue by metanav** [doctrine/DoctrineMongoODMModule#205]
doctrine/mongodb-odm 2.00-alpha1 has been released recently. Is there any plan to upgrade doctrine/DoctrineMongoODMModule? All of my applications use Zend framework so I am not able to test the new version.

**Comment by metanav** [comment]
@Ocramius there is a upgrade guide which says there is some changes:

"The constructor signature of Doctrine\ODM\MongoDB\DocumentManager as well as the create, getClient, getDocumentDatabase, getDocumentCollection, and getDocumentCollections methods have been updated to handle classes from mongodb/mongodb instead of doctrine/mongodb." 

I was just checking if doctrine/DoctrineMongoODMModule will work as is?

**Comment by Ocramius** [comment]
It will most likely not - changes will need to be made here as well, hence why I suggested you attempt an upgrade and see how much breaks.

**Comment by metanav** [comment]
I see, thanks!

**Comment by alcaeus** [comment]
I can tell you that the module is most likely not going to work with 2.0 without adjustments. I'll see when I can get to it, however the focus is on ODM itself and the Symfony bundle (as that's what I use personally). Contributions to the module are highly welcome.

**Comment by metanav** [comment]
@alcaeus Is there any plan to update it anytime soon? Please let me know if I can help, might need some guidance to start.

**Comment by alcaeus** [comment]
I most likely won't have time to work on this over the next weeks. You can take a look at the corresponding bundle PR: https://github.com/doctrine/DoctrineMongoDBBundle/pull/475 that brings basic compatibility with 2.0. If you have any questions, please don't hesitate contacting me here or in either the Symfony or Doctrine Slacks.

**Comment by datasage** [comment]
To avoid duplicating efforts, is someone already working on upgrading this to support 2.0 already?

**Comment by alcaeus** [comment]
Doctrine itself is not working on it.

**Comment by TomHAnderson** [comment]
It appears this will be a goal of the `develop` branch for Laminas.

**Comment by rieschl** [comment]
> 
> It appears this will be a goal of the `develop` branch for Laminas.

@TomHAnderson are you working on updating to odm 2.0? Because I did some work on that some time ago (very unfinisehd but already working basically) but stopped then because I'll probably need that to work on mezzio, too. I would rather do something like this one: https://github.com/DASPRiD/container-interop-doctrine.
Either way, do you want to see my progress so far? I'll probably need to rebase it onto `develop`, though.

**Comment by TomHAnderson** [comment]
@rieschl I am not working towards ODM 2.0.  

The develop branch here is in a working state and I just added Docker for testing (see the end of the README on develop for details).   I would love to see what you have.   Please create a PR on develop and let's go from there.

**Comment by TomHAnderson** [comment]
@rieschl I  had the impression you would add odm 2.0 support to this develop branch.  The project is waiting on these changes.  Can you give me a timeline for when you can put a PR in place?

If your situation has changed and you won't be doing this please let me know and I'll release this with the old odm version.  I would much prefer to include your work.

**Comment by rieschl** [comment]
@TomHAnderson Sorry. In the meantime I improved the code a bit but it's unfinished, so I don't think you can publish that. But due to the COVID incident I currently don't have much time to work on the code, but as soon I have some time I'll push it of course.
