### ISSUE TITLE
locked package?

### ISSUE THREAD

**Issue by rieschl** [doctrine/DoctrineMongoODMModule#207]
Is there a reason why the `composer.lock` file is in the repo?

But especially, why is `doctrine-module` locked to `2.1.7` in [compser.json](https://github.com/doctrine/DoctrineMongoODMModule/blob/85a7e4611a3fa85266e07eb8d0731ed1da7d54b6/composer.json#L33)?

If this is a mistake, I'm happy to submit a PR for it.

**Comment by webimpress** [comment]
@rieschl Oh.. yeah, it's a bug, should be ^2.1.7 of course ! My bad ....

**Comment by rieschl** [comment]
OK, I'll submit a PR shortly. And what about the lock file? Is that really needed? Though it [does not have any effect when requiring the package](https://getcomposer.org/doc/02-libraries.md#lock-file), I always thought that libraries should not have a `.lock` file.

**Comment by webimpress** [comment]
I would keep lock file, don't have time to explain why but for references you can read the discussion there: https://github.com/zendframework/zend-inputfilter/pull/107

**Comment by rieschl** [comment]
Ah ok. Good explanation (as usual if it comes from mwop) 😄
