### ISSUE TITLE
Last upgrade of doctrine break v0.11

### ISSUE THREAD

**Issue by Identity-labs** [doctrine/DoctrineMongoODMModule#209]
Environment : 
zendframework 2.5
zendframework/zend-stdlib 2.7.7
alcaeus/mongo-php-adapter 1.1
doctrine/doctrine-mongo-odm-module 0.11.0

We can't upgrade quickly zf

Do you have any solution for this error, since last upgrade of doctrine dependencies ?

Fatal error: Uncaught TypeError: Argument 1 passed to Doctrine\ODM\MongoDB\Configuration::setMetadataDriverImpl() must be an instance of Doctrine\Common\Persistence\Mapping\Driver\MappingDriver, instance of Doctrine\Persistence\Mapping\Driver\MappingDriverChain given, called in /vendor/doctrine/doctrine-mongo-odm-module/src/DoctrineMongoODMModule/Service/ConfigurationFactory.php on line 81 and defined in /vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Configuration.php:157

**Comment by Ocramius** [comment]
Closing: unrelated to this module.

**Comment by alcaeus** [comment]
FYI, this was a bug in doctrine/persistence that has since been fixed in 1.3.3.
