### ISSUE TITLE
Transition to Laminas

### ISSUE THREAD

**Issue by marc-jangvs** [doctrine/DoctrineMongoODMModule#210]
Now Zend made it's transition to Laminas the package need to be updated to point to the correct new packages.

**Comment by TomHAnderson** [comment]
This work is ongoing in the `develop` branch

**Comment by YuraKril** [comment]
doctrine/mongodb-odm - "version": "1.3.6"

@trigger_error(sprintf('The "%s" method is deprecated and will be removed in doctrine/mongodb-odm 2.0.', __METHOD__) for methods setRetryQuery, setRetryConnect in DoctrineMongoODMModule\Service line 69 -70

**Comment by TomHAnderson** [comment]
Created Laminas build: https://github.com/doctrine/DoctrineMongoODMModule/releases/tag/2.0.0

**Comment by TomHAnderson** [comment]
> doctrine/mongodb-odm - "version": "1.3.6"
> 
> @trigger_error(sprintf('The "%s" method is deprecated and will be removed in doctrine/mongodb-odm 2.0.', **METHOD**) for methods setRetryQuery, setRetryConnect in DoctrineMongoODMModule\Service line 69 -70

@YuraKril I'm not sure what you're reporting here.  I've moved your comment to https://github.com/doctrine/DoctrineMongoODMModule/issues/219
