### ISSUE TITLE
Deprecated message

### ISSUE THREAD

**Issue by TomHAnderson** [doctrine/DoctrineMongoODMModule#219]
doctrine/mongodb-odm - "version": "1.3.6"

@trigger_error(sprintf('The "%s" method is deprecated and will be removed in doctrine/mongodb-odm 2.0.', METHOD) for methods setRetryQuery, setRetryConnect in DoctrineMongoODMModule\Service line 69 -70

**Comment by malarzm** [comment]
This will pop up until module is updated to support ODM 2.x
