### ISSUE TITLE
relax/move laminas-hydrator

### ISSUE THREAD

**Issue by rieschl** [doctrine/DoctrineMongoODMModule#229]
Currently, `laminas/laminas-hydrator` is set as production dependency with a version constraint of `^3.0.2`. Version 4 was released some time ago and this package prevents me from upgrading.
I checked the code and the laminas-hydrator is not used at all in any `src` files, but only in a [test setup as module](https://github.com/doctrine/DoctrineMongoODMModule/blob/3.0.x/tests/TestConfiguration.php#L9) (this provides some configuration for the ServiceManager and a ServiceListener).
I tried to remove the package from composer, then version 4 is pulled (because it's required by laminas-form). The tests run fine with version 4.
So I'd suggest moving the `laminas/laminas-hydrator` package to `require-dev` with a version constraint of `"^3.0.2 || ^4.0"`.

Is that okay? Shall I open a PR with those changes?

Thanks!

**Comment by driehle** [comment]
Yes, your suggestion looks good to me. Go ahead an create a PR, I'll be happy to review and merge it!

Just an remark, if it is used in the test setup, it should be in `require-dev`, but `^3.0.2 || ^4.0.0` is fine.
