### ISSUE TITLE
Configuration template is outdated

### ISSUE THREAD

**Issue by e2video** [doctrine/DoctrineMongoODMModule#231]
Hello,
After composer update it's throwing error:
"detail": "Argument 1 passed to DoctrineMongoODMModule\\Options\\Configuration::setGenerateProxies() must be of the type int, bool given, called in /prj/vendor/laminas/laminas-stdlib/src/AbstractOptions.php on line 118"

If I set 'generate_proxies'   => 1, then I get the same error for hydrators.
when I set 'generate_hydrators' => 1 then I get:

"detail": "Service with name \"doctrine.configuration.odm_default\" could not be created. Reason: Invalid proxy generation strategy given - only AUTOGENERATE_FILE_NOT_EXISTS and AUTOGENERATE_EVAL are supported."

and I have these commented and uncommenting doesn't help:

            //    'generate_persistent_collections' => Configuration::AUTOGENERATE_ALWAYS,
            //    'persistent_collection_dir' => 'data/DoctrineMongoODMModule/PersistentCollection',
            //    'persistent_collection_namespace' => 'DoctrineMongoODMModule\PersistentCollection',

Any idea what's missing?

Thanks

**Comment by driehle** [comment]
Could you please identify which packages you have updated? 

If you ran `composer update` you may have updated several packages together. In such case you can do a rollback (hopefully you have your `composer.lock` in git), run `composer show`, then run `composer update` again and do another `composer show`. Either by comparing the output of the two `composer show` or by looking at the output of `composer update`, you should be able to tell a list of packages that you updated.

Since the last release of DoctrineMongoODMModule is from Nov 2020, I'd rather except an issue with an upstream dependency.

**Comment by e2video** [comment]
Hello Dennis and thank you for your quick response.
Very strange but I cloned my repo that was working and now I get the same error when run ./vendor/bin/doctrine-module
Will try to setup new project to see if something else is an issue and let you know

Thanks again.

**Comment by e2video** [comment]
After commenting generate_... blocks everything works fine:

//                'generate_proxies'   => true,
                //                'proxy_dir'          => 'data/DoctrineMongoODMModule/Proxy',
                //                'proxy_namespace'    => 'DoctrineMongoODMModule\Proxy',
                //
                //                'generate_hydrators' => true,
                //                'hydrator_dir'       => 'data/DoctrineMongoODMModule/Hydrator',
                //                'hydrator_namespace' => 'DoctrineMongoODMModule\Hydrator',


Looks like there is a change for using these but the template is still like this one.
Please advise.

Thanks

**Comment by driehle** [comment]
Indeed, if you look at [module.config.php](https://github.com/doctrine/DoctrineMongoODMModule/blob/3.0.x/config/module.config.php) it says:

```php

                'generate_proxies'   => Configuration::AUTOGENERATE_EVAL,
                'proxy_dir'          => 'data/DoctrineMongoODMModule/Proxy',
                'proxy_namespace'    => 'DoctrineMongoODMModule\Proxy',

                'generate_hydrators' => Configuration::AUTOGENERATE_ALWAYS,
                'hydrator_dir'       => 'data/DoctrineMongoODMModule/Hydrator',
                'hydrator_namespace' => 'DoctrineMongoODMModule\Hydrator',

                'generate_persistent_collections' => Configuration::AUTOGENERATE_ALWAYS,
                'persistent_collection_dir' => 'data/DoctrineMongoODMModule/PersistentCollection',
                'persistent_collection_namespace' => 'DoctrineMongoODMModule\PersistentCollection',
                'persistent_collection_factory' => null,
                'persistent_collection_generator' => null,
```

However, if you look [module.doctrine-mongo-odm.local.php.dist](https://github.com/doctrine/DoctrineMongoODMModule/blob/3.0.x/config/module.doctrine-mongo-odm.local.php.dist), the file our [installation guide](https://github.com/doctrine/DoctrineMongoODMModule/blob/3.0.x/docs/en/index.rst#installation) instructs you to copy, it says:

```php
//                'generate_proxies'   => true,
//                'proxy_dir'          => 'data/DoctrineMongoODMModule/Proxy',
//                'proxy_namespace'    => 'DoctrineMongoODMModule\Proxy',
//
//                'generate_hydrators' => true,
//                'hydrator_dir'       => 'data/DoctrineMongoODMModule/Hydrator',
//                'hydrator_namespace' => 'DoctrineMongoODMModule\Hydrator',
//
//                'generate_persistent_collections' => Configuration::AUTOGENERATE_ALWAYS,
//                'persistent_collection_dir' => 'data/DoctrineMongoODMModule/PersistentCollection',
//                'persistent_collection_namespace' => 'DoctrineMongoODMModule\PersistentCollection',
//                'persistent_collection_factory' => null,
//                'persistent_collection_generator' => null,
```

Would you like to create a pull request to fix this issue?

**Comment by e2video** [comment]
That works as expected.
Correct, I was using the instructions where I used module.doctrine-mongo-odm.local.php.dist and you're right it should be corrected.
Thanks!

**Comment by driehle** [comment]
I'll leave this one open as a reminder for fixing the template.

**Comment by driehle** [comment]
See [release 3.0.3](https://github.com/doctrine/DoctrineMongoODMModule/releases/tag/3.0.3).
