### ISSUE TITLE
Version 5 error class cache injection

### ISSUE THREAD

**Issue by juizmill** [doctrine/DoctrineMongoODMModule#278]
I got  this error after upgrading to version 5. 

can someone help me?

`
Fatal error: Uncaught Laminas\Di\Exception\MissingPropertyException: Could not resolve value for parameter "storage" of type Laminas\Cache\Storage\StorageInterface in class DoctrineModule\Cache\LaminasStorageCache (requested as DoctrineModule\Cache\LaminasStorageCache) in /var/www/html/vendor/laminas/laminas-di/src/Resolver/DependencyResolver.php:323 Stack trace: #0 /var/www/html/vendor/laminas/laminas-di/src/Injector.php(222): Laminas\Di\Resolver\DependencyResolver->resolveParameters() #1 /var/www/html/vendor/laminas/laminas-di/src/Injector.php(173): Laminas\Di\Injector->resolveParameters() #2 /var/www/html/vendor/laminas/laminas-di/src/Injector.php(133): Laminas\Di\Injector->createInstance() #3 /var/www/html/vendor/laminas/laminas-di/src/Container/AutowireFactory.php(61): Laminas\Di\Injector->create() #4 /var/www/html/vendor/laminas/laminas-di/src/Container/ServiceManager/AutowireFactory.php(45): Laminas\Di\Container\AutowireFactory->create() #5 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): Laminas\Di\Container\ServiceManager\AutowireFactory->__invoke() #6 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #7 /var/www/html/vendor/doctrine/doctrine-module/src/Service/CacheFactory.php(53): Laminas\ServiceManager\ServiceManager->get() #8 /var/www/html/vendor/doctrine/doctrine-module/src/ServiceFactory/AbstractDoctrineServiceFactory.php(41): DoctrineModule\Service\CacheFactory->__invoke() #9 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineModule\ServiceFactory\AbstractDoctrineServiceFactory->__invoke() #10 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #11 /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/src/Service/ConfigurationFactory.php(71): Laminas\ServiceManager\ServiceManager->get() #12 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineMongoODMModule\Service\ConfigurationFactory->__invoke() #13 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #14 /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/src/Service/ConnectionFactory.php(66): Laminas\ServiceManager\ServiceManager->get() #15 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineMongoODMModule\Service\ConnectionFactory->__invoke() #16 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #17 /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/src/Service/DocumentManagerFactory.php(27): Laminas\ServiceManager\ServiceManager->get() #18 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineMongoODMModule\Service\DocumentManagerFactory->__invoke() #19 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #20 /var/www/html/vendor/doctrine/doctrine-module/src/Service/Authentication/StorageFactory.php(38): Laminas\ServiceManager\ServiceManager->get() #21 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineModule\Service\Authentication\StorageFactory->__invoke() #22 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #23 /var/www/html/vendor/doctrine/doctrine-module/src/Service/Authentication/AuthenticationServiceFactory.php(23): Laminas\ServiceManager\ServiceManager->get() #24 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineModule\Service\Authentication\AuthenticationServiceFactory->__invoke() #25 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #26 /var/www/html/module/user/src/Service/Factory/AuthenticationServiceFactory.php(14): Laminas\ServiceManager\ServiceManager->get() #27 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): Squid\User\Service\Factory\AuthenticationServiceFactory->__invoke() #28 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #29 /var/www/html/module/application/src/Listener/Factory/AbacListenerFactory.php(18): Laminas\ServiceManager\ServiceManager->get() #30 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): Squid\Application\Listener\Factory\AbacListenerFactory->__invoke() #31 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #32 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(135): Laminas\ServiceManager\ServiceManager->get() #33 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(260): Laminas\Mvc\Application->bootstrap() #34 /var/www/html/public/index.php(54): Laminas\Mvc\Application::init() #35 {main} Next Laminas\ServiceManager\Exception\ServiceNotCreatedException: Service with name "DoctrineModule\Cache\LaminasStorageCache" could not be created. Reason: Could not resolve value for parameter "storage" of type Laminas\Cache\Storage\StorageInterface in class DoctrineModule\Cache\LaminasStorageCache (requested as DoctrineModule\Cache\LaminasStorageCache) in /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:649 Stack trace: #0 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #1 /var/www/html/vendor/doctrine/doctrine-module/src/Service/CacheFactory.php(53): Laminas\ServiceManager\ServiceManager->get() #2 /var/www/html/vendor/doctrine/doctrine-module/src/ServiceFactory/AbstractDoctrineServiceFactory.php(41): DoctrineModule\Service\CacheFactory->__invoke() #3 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineModule\ServiceFactory\AbstractDoctrineServiceFactory->__invoke() #4 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #5 /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/src/Service/ConfigurationFactory.php(71): Laminas\ServiceManager\ServiceManager->get() #6 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineMongoODMModule\Service\ConfigurationFactory->__invoke() #7 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #8 /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/src/Service/ConnectionFactory.php(66): Laminas\ServiceManager\ServiceManager->get() #9 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineMongoODMModule\Service\ConnectionFactory->__invoke() #10 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #11 /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/src/Service/DocumentManagerFactory.php(27): Laminas\ServiceManager\ServiceManager->get() #12 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineMongoODMModule\Service\DocumentManagerFactory->__invoke() #13 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #14 /var/www/html/vendor/doctrine/doctrine-module/src/Service/Authentication/StorageFactory.php(38): Laminas\ServiceManager\ServiceManager->get() #15 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineModule\Service\Authentication\StorageFactory->__invoke() #16 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #17 /var/www/html/vendor/doctrine/doctrine-module/src/Service/Authentication/AuthenticationServiceFactory.php(23): Laminas\ServiceManager\ServiceManager->get() #18 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): DoctrineModule\Service\Authentication\AuthenticationServiceFactory->__invoke() #19 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #20 /var/www/html/module/user/src/Service/Factory/AuthenticationServiceFactory.php(14): Laminas\ServiceManager\ServiceManager->get() #21 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): Squid\User\Service\Factory\AuthenticationServiceFactory->__invoke() #22 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #23 /var/www/html/module/application/src/Listener/Factory/AbacListenerFactory.php(18): Laminas\ServiceManager\ServiceManager->get() #24 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(642): Squid\Application\Listener\Factory\AbacListenerFactory->__invoke() #25 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(264): Laminas\ServiceManager\ServiceManager->doCreate() #26 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(135): Laminas\ServiceManager\ServiceManager->get() #27 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(260): Laminas\Mvc\Application->bootstrap() #28 /var/www/html/public/index.php(54): Laminas\Mvc\Application::init() #29 {main} thrown in /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php on line 649
`

**Comment by driehle** [comment]
This could actually be the issue reported in doctrine/DoctrineModule#815. Please check the discussion there.
