### ISSUE TITLE
`Configuration::setMetadataCacheImpl` is deprecated since mongodb-odm 2.2

### ISSUE THREAD

**Issue by rieschl** [doctrine/DoctrineMongoODMModule#279]
Hey!

The method `\Doctrine\ODM\MongoDB\Configuration::setMetadataCacheImpl` [was deprecated in `monbodb-odm` `2.2`](https://github.com/doctrine/mongodb-odm/blob/69e64e7eb51f07bcfc09bc8e7ea8329f301b44ff/lib/Doctrine/ODM/MongoDB/Configuration.php#L204C30-L204C30).
This package calls it in the [ConfigurationFactory](https://github.com/doctrine/DoctrineMongoODMModule/blob/2f0c1465d130c8170d51984faa26c43c20da8f6a/src/Service/ConfigurationFactory.php#L71), though.

Are there plans to upgrade this package to avoid the deprecation warning? Should I have a look at it?
At first glance, the most simple fix would be wrapping the current cache implementation (`CacheAdapter::wrap($cacheImpl)`) and call `setMetadataCache()` instead of `setMetadataCacheImpl()`. Maybe checking if the cache returned by `$container->get($configurationOptions->getMetadataCache())` is already a PSR-6 cache, to be forward compatible.

Thanks!

**Comment by driehle** [comment]
Closed by #280
